// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCcGBfnNQ6aXBEIAfS7leXCQbwZRhDGQRM',
    appId: '1:765859414312:web:efd5972435c9b0fe08501d',
    messagingSenderId: '765859414312',
    projectId: 'stackecom-b1331',
    authDomain: 'stackecom-b1331.firebaseapp.com',
    storageBucket: 'stackecom-b1331.appspot.com',
    measurementId: 'G-RKZFMRHPB2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0WyMrkcYg_RcHuqq-o7IKf-MeuBmAJik',
    appId: '1:765859414312:android:8e039904d80f1aa908501d',
    messagingSenderId: '765859414312',
    projectId: 'stackecom-b1331',
    storageBucket: 'stackecom-b1331.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBi1dYsCcPcRp8NOZzRokmR6G2pKahRDpw',
    appId: '1:765859414312:ios:eac5d7de9757e49808501d',
    messagingSenderId: '765859414312',
    projectId: 'stackecom-b1331',
    storageBucket: 'stackecom-b1331.appspot.com',
    iosBundleId: 'com.example.ecomstack',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBi1dYsCcPcRp8NOZzRokmR6G2pKahRDpw',
    appId: '1:765859414312:ios:0c3a4f1deeeae6c008501d',
    messagingSenderId: '765859414312',
    projectId: 'stackecom-b1331',
    storageBucket: 'stackecom-b1331.appspot.com',
    iosBundleId: 'com.example.ecomstack.RunnerTests',
  );
}
